# Generated by Django 2.2.1 on 2019-05-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0002_crear_usuario_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('sigla', models.CharField(default='', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
                'ordering': ['-id'],
            },
        ),
    ]
