# Generated by Django 2.2.1 on 2019-05-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0003_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('sigla', models.CharField(default='', max_length=4)),
                ('pais', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='presentes.Pais')),
            ],
            options={
                'verbose_name_plural': 'provincias',
                'db_table': 'provincias',
                'ordering': ['-id'],
            },
        ),
    ]
