# Generated by Django 2.2.1 on 2019-05-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.CharField(default='', max_length=200)),
                ('provincia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='presentes.Provincia')),
            ],
            options={
                'verbose_name_plural': 'organizaciones',
                'db_table': 'organizaciones',
                'ordering': ['-id'],
            },
        ),
    ]
