# Generated by Django 2.2.1 on 2019-05-08 15:01

from django.db import migrations

def crear_pais_argentina(apps, schema_editor):
    PaisModel = apps.get_model("presentes", "Pais")
    paises = [("Argentina", "AR"),]

    for pais in paises:
        PaisModel.objects.create(nombre=pais[0], sigla=pais[1])

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0006_organizacion'),
    ]

    operations = [
        migrations.RunPython(crear_pais_argentina, migrations.RunPython.noop)
    ]
