# Generated by Django 2.2.1 on 2019-05-08 15:07

from django.db import migrations

def crear_provincias_argentinas(apps, schema_editor):
    PaisModel = apps.get_model("presentes", "Pais")
    ProvinciaModel = apps.get_model("presentes", "Provincia")

    Argentina = PaisModel.objects.get(nombre="Argentina")
    provincias = [
        ("Buenos Aires","PBA"),
        ("Catamarca","CA"),
        ("Chaco","CH"),
        ("Chubut","CT"),
        ("Ciudad Autónoma de Buenos Aires","CABA"),
        ("Córdoba","CB"),
        ("Corrientes","CR"),
        ("Entre Ríos","ER"),
        ("Formosa","FO"),
        ("Jujuy","JY"),
        ("La Pampa","LP"),
        ("La Rioja","LR"),
        ("Mendoza","MZ"),
        ("Misiones","MI"),
        ("Neuquén","NQ"),
        ("Río Negro","RN"),
        ("Salta","SA"),
        ("San Juan","SJ"),
        ("San Luis","SL"),
        ("Santa Cruz","SC"),
        ("Santa Fe","SF"),
        ("Santiago del Estero","SE"),
        ("Tierra del Fuego, Antártida e Islas del Atlántico Sur","TF"),
        ("Tucumán","TU"),
    ]

    for provincia in provincias:
        ProvinciaModel.objects.create(nombre=provincia[0], sigla=provincia[1], pais=Argentina)

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0007_crear_pais_argentina'),
    ]

    operations = [
        migrations.RunPython(crear_provincias_argentinas, migrations.RunPython.noop)
    ]
