# Generated by Django 2.2.1 on 2019-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0008_crear_provincias_argentinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'etiquetas',
                'db_table': 'etiquetas',
                'ordering': ['-id'],
            },
        ),
    ]
