# Generated by Django 2.2.1 on 2019-05-10 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0009_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('apellido', models.CharField(default='', max_length=200)),
                ('localidad', models.CharField(default='', max_length=200)),
                ('latitud', models.CharField(default='', max_length=20)),
                ('longitud', models.CharField(default='', max_length=20)),
                ('fecha_de_creacion', models.DateField(default=datetime.date.today)),
                ('categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.Categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, default=None, related_name='casos', to='presentes.Etiqueta')),
                ('provincia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.Provincia')),
            ],
            options={
                'verbose_name_plural': 'casos',
                'db_table': 'casos',
                'ordering': ['-id'],
            },
        ),
    ]
