# Generated by Django 2.2.1 on 2019-05-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0011_caso_fecha_del_hecho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'provincias'},
        ),
    ]
