# Generated by Django 2.2.1 on 2019-05-22 16:34

from django.db import migrations

def crear_categorias(apps, schema_editor):
    CategoriaModel = apps.get_model("presentes", "Categoria")

    categorias = [
        "Ataques",
        "Travesticidio Social",
        "Asesinatos"
    ]

    for categoria in categorias:
        CategoriaModel.objects.create(nombre=categoria)

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0013_auto_20190521_1432'),
    ]

    operations = [
        migrations.RunPython(crear_categorias, migrations.RunPython.noop)
    ]
