# Generated by Django 2.2.1 on 2019-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0014_crear_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='lugar_del_hecho',
            field=models.CharField(default='', max_length=250),
        ),
    ]
