# Generated by Django 2.2.1 on 2019-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0016_auto_20190523_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='localidad',
            field=models.CharField(default='', max_length=200),
        ),
    ]
