# Generated by Django 2.2.1 on 2019-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0017_organizacion_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeCaso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Estados de Caso',
                'db_table': 'estados-de-caso',
                'ordering': ['-id'],
            },
        ),
    ]
