# Generated by Django 2.2.1 on 2019-05-28 14:14

from django.db import migrations

def crear_estados_de_caso(apps, schema_editor):
    EstadoDeCasoModel = apps.get_model("presentes", "EstadoDeCaso")

    estados = [
        "Pendiente de validación",
        "Público",
        "Privado",
    ]

    for estado in estados:
        EstadoDeCasoModel.objects.create(nombre=estado)

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0018_estadodecaso'),
    ]

    operations = [
        migrations.RunPython(crear_estados_de_caso, migrations.RunPython.noop)
    ]
