# Generated by Django 2.2.1 on 2019-05-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0019_crear_estados_de_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estado_de_publicacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.EstadoDeCaso'),
        ),
    ]
