# Generated by Django 2.2.1 on 2019-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0020_caso_estado_de_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='anio_de_llegada',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='caso',
            name='ante_quien_se_hizo_la_denuncia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='causa_de_la_muerte',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='es_migrante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caso',
            name='hay_denuncia',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('NS', 'No sabe')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='la_denuncia_reconoce_genero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caso',
            name='pais_de_origen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='por_que_no_denuncio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
