# Generated by Django 2.2.1 on 2019-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0021_auto_20190528_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='lugar_del_hecho',
        ),
        migrations.AddField(
            model_name='caso',
            name='edad',
            field=models.CharField(default='', max_length=3),
        ),
    ]
