# Generated by Django 2.2.1 on 2019-05-29 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0022_auto_20190529_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fecha_de_denuncia',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='la_denuncia_reconoce_genero',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
    ]
