# Generated by Django 2.2.1 on 2019-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0023_auto_20190529_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='es_migrante',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
    ]
