# Generated by Django 2.2.1 on 2019-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0024_auto_20190529_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='lugar_de_nacimiento',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
