# Generated by Django 2.2.1 on 2019-05-29 19:58

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def crear_permisos_de_usuarios(app, schema_editor):
    grupo = Group.objects.get(name="Administrador")

    tipo = ContentType.objects.get(app_label='presentes', model=grupo)

    permiso_listar = Permission.objects.create(name='casos', codename='casos.puede_listar', content_type=tipo)
    permiso_crear = Permission.objects.create(name='casos', codename='casos.puede_crear', content_type=tipo)
    permiso_eliminar = Permission.objects.create(name='casos', codename='casos.puede_eliminar', content_type=tipo)
    permiso_editar = Permission.objects.create(name='casos', codename='casos.puede_editar', content_type=tipo)
    permiso_validar = Permission.objects.create(name='casos', codename='casos.puede_validar', content_type=tipo)

    grupo.permissions.add(permiso_listar)
    grupo.permissions.add(permiso_crear)
    grupo.permissions.add(permiso_eliminar)
    grupo.permissions.add(permiso_editar)
    grupo.permissions.add(permiso_validar)

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0026_crear_grupo_administrador'),
    ]

    operations = [
        migrations.RunPython(crear_permisos_de_usuarios, migrations.RunPython.noop),
    ]
