# Generated by Django 2.2.1 on 2019-05-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0027_crear_permisos_de_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='cj_anio_de_inicio',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_cuenta_con_defensa',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_donde_se_tramita',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_hay_informe_forense',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_hubo_violencia_institucional',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_instancia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_organismos_publicos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_organizaciones',
            field=models.ManyToManyField(blank=True, default=None, related_name='casos', to='presentes.Organizacion'),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_respetaron_nombre_de_ig',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_violencia_institucion_localidad',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_violencia_institucion_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_violencia_institucion_provincia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_cj_violencia', to='presentes.Provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='donde_vivia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='estaba_en_situacion_de_calle',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='estudios_cursados',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='hay_causa_judicial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('NS', 'No sabe')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='localidad_del_penal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='nombre_de_quien_brindo_informacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='nombre_del_penal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='obra_social',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='caso',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='prestaciones_de_salud',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='provincia_del_penal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_penal', to='presentes.Provincia'),
        ),
        migrations.AddField(
            model_name='caso',
            name='telefono_de_quien_brindo_informacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='tenia_obra_social',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='tenia_prision_preventiva',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='tiene_acceso_a_prestaciones_de_salud',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='titulo_de_la_causa_en_la_justicia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
