# Generated by Django 2.2.1 on 2019-05-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0030_auto_20190530_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='cj_numero_de_la_causa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='caso',
            name='cj_titulo_de_la_causa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
