# Generated by Django 2.2.1 on 2019-05-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0032_auto_20190530_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='cj_hubo_violencia_institucional',
            new_name='hubo_violencia_institucional',
        ),
        migrations.RenameField(
            model_name='caso',
            old_name='cj_violencia_institucion_localidad',
            new_name='violencia_institucion_localidad',
        ),
        migrations.RenameField(
            model_name='caso',
            old_name='cj_violencia_institucion_nombre',
            new_name='violencia_institucion_nombre',
        ),
        migrations.RemoveField(
            model_name='caso',
            name='cj_violencia_institucion_provincia',
        ),
        migrations.AddField(
            model_name='caso',
            name='violencia_institucion_provincia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_violencia_institucional', to='presentes.Provincia'),
        ),
    ]
