# Generated by Django 2.2.1 on 2019-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0033_auto_20190530_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='causa_de_la_muerte',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_anio_de_inicio',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_donde_se_tramita',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_instancia',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_numero_de_la_causa',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_organismos_publicos',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_titulo_de_la_causa',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='localidad_del_penal',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre_del_penal',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='obra_social',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='por_que_no_denuncio',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='prestaciones_de_salud',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='titulo_de_la_causa_en_la_justicia',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='violencia_institucion_localidad',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='violencia_institucion_nombre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
