# Generated by Django 2.2.1 on 2019-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0034_auto_20190530_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='anio_de_llegada',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='ante_quien_se_hizo_la_denuncia',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='donde_vivia',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estudios_cursados',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='nombre_de_quien_brindo_informacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='pais_de_origen',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='telefono_de_quien_brindo_informacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
