# Generated by Django 2.2.1 on 2019-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0036_auto_20190603_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='copete',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='link_a_nota',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
