# Generated by Django 2.2.1 on 2019-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0038_auto_20190604_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='prostitucion',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
    ]
