# Generated by Django 2.2.1 on 2019-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0039_caso_prostitucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='hay_causa_judicial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('NS', 'No sabe'), ('NT', 'No se la tomaron')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='hay_denuncia',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('NS', 'No sabe'), ('NT', 'No se la tomaron')], default=None, max_length=2, null=True),
        ),
    ]
