# Generated by Django 2.2.1 on 2019-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0040_auto_20190605_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estaba_detenida',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
    ]
