# Generated by Django 2.2.1 on 2019-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0042_auto_20190605_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
