# Generated by Django 2.2.1 on 2019-06-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0043_auto_20190611_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
