# Generated by Django 2.2.1 on 2019-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0045_auto_20190613_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='desde_cuando_estaba_encerrada',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
