# Generated by Django 2.2.1 on 2019-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0046_caso_desde_cuando_estaba_encerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='referente',
            field=models.CharField(default='', max_length=200),
        ),
    ]
