# Generated by Django 2.2.1 on 2019-06-14 17:44

from django.db import migrations

def crear_etiquetas_de_genero(apps, schema_editor):
    EtiquetaModel = apps.get_model("presentes", "Etiqueta")

    etiquetas = [
        "Travesticido/Transfemicidio",
        "Varón trans/hombre trans",
        "Lesbiana",
        "Gay",
        "No binarie",
        "Intersex",
        "+",
        "Por vínculo"
    ]

    for etiqueta in etiquetas:
        EtiquetaModel.objects.create(nombre=etiqueta)

class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0047_organizacion_referente'),
    ]

    operations = [
        migrations.RunPython(crear_etiquetas_de_genero, migrations.RunPython.noop)
    ]
