# Generated by Django 2.2.1 on 2019-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0048_crear_etiquetas_de_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='cj_otrasOrganizaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
