# Generated by Django 2.2.1 on 2019-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0050_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='cj_organizaciones',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='casos', to='presentes.Organizacion'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='casos', to='presentes.Etiqueta'),
        ),
    ]
