# Generated by Django 2.2.1 on 2019-08-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0051_auto_20190813_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='descripcion_del_hecho',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
