# Generated by Django 2.2.1 on 2019-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0053_auto_20190813_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='hay_causa_judicial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('SD', 'Sin determinar')], default=None, max_length=2, null=True),
        ),
    ]
