# Generated by Django 2.2.1 on 2019-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0054_auto_20190813_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='denuncia_organizaciones',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='casos_denuncia', to='presentes.Organizacion'),
        ),
    ]
