# Generated by Django 2.2.1 on 2019-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0055_caso_denuncia_organizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
