# Generated by Django 2.2.1 on 2019-08-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0057_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='que_estudios_tiene',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.Estudio'),
        ),
    ]
