# Generated by Django 2.2.1 on 2019-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0058_caso_que_estudios_tiene'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='latitud',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='longitud',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
