# Generated by Django 2.2.1 on 2019-08-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0059_auto_20190816_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='que_estudios_tiene',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.Estudio'),
        ),
    ]
