# Generated by Django 2.2.1 on 2019-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0060_auto_20190819_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='la_victima_conocia_al_victimario',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cj_organizaciones',
            field=models.ManyToManyField(blank=True, default=None, related_name='casos', to='presentes.Organizacion'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='denuncia_organizaciones',
            field=models.ManyToManyField(blank=True, default=None, related_name='casos_denuncia', to='presentes.Organizacion'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, default=None, related_name='casos', to='presentes.Etiqueta'),
        ),
    ]
