# Generated by Django 2.2.1 on 2019-08-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0062_lugardelhecho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugardelhecho',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Lugares del Hecho'},
        ),
        migrations.AddField(
            model_name='caso',
            name='donde_ocurrio_el_hecho',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.LugarDelHecho'),
        ),
    ]
