# Generated by Django 2.2.1 on 2019-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0063_auto_20190822_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioPrivado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Espacios Privados',
                'db_table': 'espacios_privados',
                'ordering': ['-id'],
            },
        ),
    ]
