# Generated by Django 2.2.1 on 2019-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0065_auto_20190823_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanicaDelHecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Mécanicas del hecho',
                'db_table': 'mecanicas_del_hecho',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='espacioprivado',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Espacios Privados'},
        ),
        migrations.AlterModelOptions(
            name='lugardelhecho',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Lugares del Hecho'},
        ),
    ]
