# Generated by Django 2.2.1 on 2019-08-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0066_auto_20190823_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='mecanica_del_hecho',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.MecanicaDelHecho'),
        ),
    ]
