# Generated by Django 2.2.1 on 2019-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0067_caso_mecanica_del_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='mecanica_del_hecho_otro',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
