# Generated by Django 2.2.1 on 2019-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0068_caso_mecanica_del_hecho_otro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'db_table': 'instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='mecanicadelhecho',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Mécanicas del hecho'},
        ),
    ]
