# Generated by Django 2.2.1 on 2019-08-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0069_auto_20190823_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='institucion_involucrada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.Institucion'),
        ),
    ]
