# Generated by Django 2.2.1 on 2020-02-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0071_caso_institucion_involucrada_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='donde_ocurrio_el_hecho',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.LugarDelHecho'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='espacio_privado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.EspacioPrivado'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='mecanica_del_hecho',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='presentes.MecanicaDelHecho'),
        ),
    ]
